pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'Java17'
    }

    environment {
        PATH = "C:\\Program Files\\Docker\\Docker\\resources\\bin;${env.PATH}"
        DOCKERHUB_CREDENTIALS_ID = 'Docker_Hub'
        DOCKERHUB_REPO = 'sakarihonkavaara/tempconverter'
        DOCKER_IMAGE_TAG = 'latest'
    }

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/Sakarihon/OTP_1_inclass_assignment.git'
            }
        }

        stage('Run Tests') {
            steps {
                dir('OTP1_inclass_assignment') {
                    bat 'mvn clean test'
                }
            }
        }

        stage('Code Coverage') {
            steps {
                dir('OTP1_inclass_assignment') {
                    bat 'mvn jacoco:report'
                }
            }
        }

        stage('Publish Test Results') {
            steps {
                junit 'OTP1_inclass_assignment/target/surefire-reports/*.xml'
            }
        }

        stage('Publish Coverage Report') {
            steps {
                jacoco(execPattern: 'OTP1_inclass_assignment/target/jacoco.exec')
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('OTP1_inclass_assignment') {
                    script {
                        docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}")
                    }
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                        docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push()
                    }
                }
            }
        }

    }

    post {
        always {
            cleanWs()
        }
    }
}